/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import entities.Exercicio;
import entities.Treino;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author marco
 */
public class FrmAdicionarTreino extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdicionarTreino
     */
    public FrmAdicionarTreino() {
        initComponents();
    }
    private Treino treino = new Treino();
    List<Long> ids = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbEx1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbEx2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbEx3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbEx4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbEx5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbEx6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbEx7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbEx8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbEx9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbEx10 = new javax.swing.JLabel();
        btnAddTreino = new javax.swing.JButton();
        btnAddEx1 = new javax.swing.JButton();
        btnAddEx2 = new javax.swing.JButton();
        btnAddEx3 = new javax.swing.JButton();
        btnAddEx4 = new javax.swing.JButton();
        btnAddEx5 = new javax.swing.JButton();
        btnAddEx6 = new javax.swing.JButton();
        btnAddEx7 = new javax.swing.JButton();
        btnAddEx8 = new javax.swing.JButton();
        btnAddEx9 = new javax.swing.JButton();
        btnAddEx10 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        txtNomeTreino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Treino");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 1"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbEx1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 2"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbEx2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 3"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbEx3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 4"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbEx4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 5"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lbEx5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 6"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lbEx6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 7"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEx7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 8"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEx8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 9"));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEx9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercício 10"));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEx10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEx10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAddTreino.setText("Adicionar Treino");
        btnAddTreino.setEnabled(false);
        btnAddTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTreinoActionPerformed(evt);
            }
        });

        btnAddEx1.setText("Adicionar exercício");
        btnAddEx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx1ActionPerformed(evt);
            }
        });

        btnAddEx2.setText("Adicionar exercício");
        btnAddEx2.setEnabled(false);
        btnAddEx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx2ActionPerformed(evt);
            }
        });

        btnAddEx3.setText("Adicionar exercício");
        btnAddEx3.setEnabled(false);
        btnAddEx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx3ActionPerformed(evt);
            }
        });

        btnAddEx4.setText("Adicionar exercício");
        btnAddEx4.setEnabled(false);
        btnAddEx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx4ActionPerformed(evt);
            }
        });

        btnAddEx5.setText("Adicionar exercício");
        btnAddEx5.setEnabled(false);
        btnAddEx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx5ActionPerformed(evt);
            }
        });

        btnAddEx6.setText("Adicionar exercício");
        btnAddEx6.setEnabled(false);
        btnAddEx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx6ActionPerformed(evt);
            }
        });

        btnAddEx7.setText("Adicionar exercício");
        btnAddEx7.setEnabled(false);
        btnAddEx7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx7ActionPerformed(evt);
            }
        });

        btnAddEx8.setText("Adicionar exercício");
        btnAddEx8.setEnabled(false);
        btnAddEx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx8ActionPerformed(evt);
            }
        });

        btnAddEx9.setText("Adicionar exercício");
        btnAddEx9.setEnabled(false);
        btnAddEx9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx9ActionPerformed(evt);
            }
        });

        btnAddEx10.setText("Adicionar exercício");
        btnAddEx10.setEnabled(false);
        btnAddEx10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx10ActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do treino"));

        txtNomeTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeTreinoActionPerformed(evt);
            }
        });
        txtNomeTreino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeTreinoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeTreino)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(txtNomeTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddEx6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnAddTreino)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddEx4)
                            .addComponent(btnAddEx1)
                            .addComponent(btnAddEx2)
                            .addComponent(btnAddEx3)
                            .addComponent(btnAddEx5)
                            .addComponent(btnAddEx7)
                            .addComponent(btnAddEx8)
                            .addComponent(btnAddEx9)
                            .addComponent(btnAddEx10))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx2, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx3, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx4, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx5, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnAddEx6, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnAddEx7))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAddEx8))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddEx9))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddEx10))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTreino)
                    .addComponent(btnLimpar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx1ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
            Exercicio exercicio;
            RestTemplate req = new RestTemplate();
            exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
            ids.add(frm.getEscolha());
            lbEx1.setText(exercicio.toString());
            treino.getExercicios().add(exercicio);
            btnAddEx1.setEnabled(false);
            btnAddEx2.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx1ActionPerformed

    private void btnAddEx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx2ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx2.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx2.setEnabled(false);
           btnAddEx3.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx2ActionPerformed

    private void btnAddEx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx3ActionPerformed
       FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx3.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx3.setEnabled(false);
           btnAddEx4.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx3ActionPerformed

    private void btnAddEx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx4ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx4.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx4.setEnabled(false);
           btnAddEx5.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx4ActionPerformed

    private void btnAddEx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx5ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx5.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx5.setEnabled(false);
           btnAddEx6.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx5ActionPerformed

    private void btnAddEx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx6ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx6.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx6.setEnabled(false);
           btnAddEx7.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx6ActionPerformed

    private void btnAddEx7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx7ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx7.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx7.setEnabled(false);
           btnAddEx8.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx7ActionPerformed

    private void btnAddEx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx8ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx8.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx8.setEnabled(false);
           btnAddEx9.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx8ActionPerformed

    private void btnAddEx9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx9ActionPerformed
        FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx9.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx9.setEnabled(false);
           btnAddEx10.setEnabled(true);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx9ActionPerformed

    private void btnAddEx10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx10ActionPerformed
       FrmEscolherEx frm = new FrmEscolherEx();
        frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
           if(frm.getEscolha()==0){
               dispose();
           }
           else{
           Exercicio exercicio;
           RestTemplate req = new RestTemplate();
           exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, frm.getEscolha());
           ids.add(frm.getEscolha());
           lbEx10.setText(exercicio.toString());
           treino.getExercicios().add(exercicio);
           btnAddEx10.setEnabled(false);
           }
        }
    });
        frm.setVisible(true);
    }//GEN-LAST:event_btnAddEx10ActionPerformed

    private void btnAddTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTreinoActionPerformed
        if(treino.getExercicios().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, adicione pelo menos um exercício");
        }else{
            RestTemplate req = new RestTemplate();
            treino.setNome(txtNomeTreino.getText());
            req.postForObject("http://localhost:8080/treino", treino, Treino.class);
            treino = new Treino();
            JOptionPane.showMessageDialog(null, "Treino adicionado com sucesso");
            dispose();
        }
    }//GEN-LAST:event_btnAddTreinoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnAddTreino.setEnabled(false);
        txtNomeTreino.setText("");
        treino = new Treino();
        RestTemplate req = new RestTemplate();
        for (Long id : ids) {
            req.delete("http://localhost:8080/exercicio/{id}", id);
            lbEx1.setText("");
            lbEx2.setText("");
            lbEx3.setText("");
            lbEx4.setText("");
            lbEx5.setText("");
            lbEx6.setText("");
            lbEx7.setText("");
            lbEx8.setText("");
            lbEx9.setText("");
            lbEx10.setText("");
            btnAddEx1.setEnabled(true);
            btnAddEx2.setEnabled(false);
            btnAddEx3.setEnabled(false);
            btnAddEx4.setEnabled(false);
            btnAddEx5.setEnabled(false);
            btnAddEx6.setEnabled(false);
            btnAddEx7.setEnabled(false);
            btnAddEx8.setEnabled(false);
            btnAddEx9.setEnabled(false);
            btnAddEx10.setEnabled(false);
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNomeTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeTreinoActionPerformed
     
    }//GEN-LAST:event_txtNomeTreinoActionPerformed

    private void txtNomeTreinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeTreinoKeyTyped
          if(!txtNomeTreino.getText().equals("")){
            btnAddTreino.setEnabled(true);
        }else{
            btnAddTreino.setEnabled(false);
        }
    }//GEN-LAST:event_txtNomeTreinoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdicionarTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEx1;
    private javax.swing.JButton btnAddEx10;
    private javax.swing.JButton btnAddEx2;
    private javax.swing.JButton btnAddEx3;
    private javax.swing.JButton btnAddEx4;
    private javax.swing.JButton btnAddEx5;
    private javax.swing.JButton btnAddEx6;
    private javax.swing.JButton btnAddEx7;
    private javax.swing.JButton btnAddEx8;
    private javax.swing.JButton btnAddEx9;
    private javax.swing.JButton btnAddTreino;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbEx1;
    private javax.swing.JLabel lbEx10;
    private javax.swing.JLabel lbEx2;
    private javax.swing.JLabel lbEx3;
    private javax.swing.JLabel lbEx4;
    private javax.swing.JLabel lbEx5;
    private javax.swing.JLabel lbEx6;
    private javax.swing.JLabel lbEx7;
    private javax.swing.JLabel lbEx8;
    private javax.swing.JLabel lbEx9;
    private javax.swing.JTextField txtNomeTreino;
    // End of variables declaration//GEN-END:variables
}
