/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import entities.Exercicio;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author marco
 */
public class FrmConsultaRecorde extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultaRecorde
     */
    public FrmConsultaRecorde() {
        initComponents();
        loadExercicios();
    }
    
    public void loadExercicios() {
        RestTemplate req = new RestTemplate();
        
        Exercicio exercicio;
        for(int i=1; i<48; i++){
            exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, i);
            cbEscolheEx.addItem(exercicio.toString());
        }
    }
    
    public void setTexto(int id){
        Exercicio exercicio;
        RestTemplate req = new RestTemplate();
        exercicio = req.getForObject("http://localhost:8080/exercicio/{id}", Exercicio.class, id); 
        if(exercicio.getRecordeCarga()==0){
            lbTexto.setText("Ainda não há registro de treino com este exercício");
        }else{
            lbTexto.setText("Seu recorde para esse exercício é: " + exercicio.getRecordeCarga()+ " kg");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbEscolheEx = new javax.swing.JComboBox<>();
        lbTexto = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recorde pessoal");
        setLocation(new java.awt.Point(290, 290));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o exercício"));

        lbTexto.setText("Pressione OK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEscolheEx, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbEscolheEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        Object item = cbEscolheEx.getSelectedItem();
        String itemSelecionado = item.toString();
        
        switch(itemSelecionado){
               case "Afundo": setTexto(1);
               break;
               case "Agachamento búlgaro" : setTexto(2);
               break;
               case "Agachamento livre" : setTexto(3);
               break;
               case "Barra fixa" : setTexto(4);
               break;
               case "Cadeira extensora" : setTexto(5);
               break;
               case "Cadeira flexora" : setTexto(6);
               break;
               case "Coice" : setTexto(7);
               break;
               case "Cross-over polia alta" : setTexto(8);
               break;
               case "Cross-over polia baixa" : setTexto(9);
               break;
               case "Cross-over polia média" : setTexto(10);
               break;
               case "Desenvolvimento halteres" : setTexto(11);
               break;
               case "Desenvolvimento militar" : setTexto(12);
               break;
               case "Elevação frontal" : setTexto(13);
               break;
               case "Elevação lateral halteres" : setTexto(14);
               break;
               case "Elevação lateral polia" : setTexto(15);
               break;
               case "Elevação pélvica" : setTexto(16);
               break;
               case "Gêmeos sentado" : setTexto(17);
               break;
               case "Leg-press" : setTexto(18);
               break;
               case "Levantamento terra" : setTexto(19);
               break;
               case "Martelo halteres" : setTexto(20);
               break;
               case "Mesa flexora" : setTexto(21);
               break;
               case "Panturrilha em pé" : setTexto(22);
               break;
               case "Panturrilha leg-press" : setTexto(23);
               break;
               case "Puxada frontal barra" : setTexto(24);
               break;
               case "Puxada frontal triângulo" : setTexto(25);
               break;
               case "Remada baixa" : setTexto(26);
               break;
               case "Remada cavalinho" : setTexto(27);
               break;
               case "Remada curvada" : setTexto(28);
               break;
               case "Rosca banco inclinado" : setTexto(29);
               break;
               case "Rosca concentrada" : setTexto(30);
               break;
                case "Rosca direta barra" : setTexto(31);
               break;
                case "Rosca direta halteres" : setTexto(32);
               break;
                case "Rosca Scott" : setTexto(33);
               break;
               case "Serrote" : setTexto(34);
               break;
               case "Stiff" : setTexto(35);
               break;
               case "Supino declinado barra" : setTexto(36);
               break;
               case "Supino inclinado barra" : setTexto(37);
               break;
               case "Supino inclinado halteres" : setTexto(38);
               break;
               case "Supino reto barra" : setTexto(39);
               break;
               case "Supino reto halteres" : setTexto(40);
               break;
               case "Triceps frânces polia" : setTexto(41);
               break;
               case "Triceps frânces halteres" : setTexto(42);
               break;
               case "Triceps pulley barra" : setTexto(43);
               break;
               case "Triceps pulley corda" : setTexto(44);
               break;
               case "Triceps testa halteres" : setTexto(45);
               break;
               case "Triceps testa polia" : setTexto(46);
               break;
               case "Voador inverso" : setTexto(47);
               break;
               
           }
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaRecorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaRecorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaRecorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaRecorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultaRecorde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbEscolheEx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTexto;
    // End of variables declaration//GEN-END:variables
}
